import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { DepositModal } from '../components'

const Home: NextPage = (props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>APWinery</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ConnectButton accountStatus="address" chainStatus="icon" />
        <h1 className={styles.title}>
          Welcome to APWinery
        </h1>

        <p className={styles.description}>
          Get started with the lottery!
        </p>
        <DepositModal />
      </main>
      <footer className={styles.footer}>
        <a href="https://rainbow.me" target="_blank" rel="noopener noreferrer">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
